name: Domenico Luciani
title: Domenico Luciani
description: "Software engineer, runner, maker, computer vision fanatic and IT security lover."
meta_description: "programming, coding, security, computer science"
permalink: '/:year/:month/:day/:title.html'
mastodon: dlion@mastodon.social

markdown: kramdown
logo: false
paginate: 15
baseurl: 
domain_name: 'https://domenicoluciani.com'
google_analytics: false
navigation:
    - label: Home
    - url: /

include: ["/.well-known" ]
# Details for the RSS feed generator
url:            'https://domenicoluciani.com'
author:         'Domenico Luciani'
bio: 'Software engineer, runner, maker, computer vision fanatic and IT security lover.'
links: ['InnerSpace 🚀 Newsletter: <a href="https://innerspace.domenicoluciani.com">https://innerspace.domenicoluciani.com</a>', 'Linkedin: <a href="https://linkedin.com/in/dlion">https://linkedin.com/in/dlion</a>', 'Github: <a href="https://github.com/dlion">https://github.com/dlion</a>']
location: Remote, Spain
website: https://domenicoluciani.com
plugins:
    - jekyll-feed
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-github-metadata
collections:
  category:
    output: true
    permalink: /category/:path/

repository: dlion/domenicoluciani

posts_dir: /assets/images/posts
covers_dir: /assets/images/covers
