name: Domenico Luciani
meta_description: "programming, coding, security, computer science"
permalink: '/:year/:month/:day/:title.html'

markdown: kramdown
logo: false
paginate: 15
baseurl: 
domain_name: 'https://domenicoluciani.com'
google_analytics: false
navigation:
    - label: Home
    - url: /

# Details for the RSS feed generator
url:            'https://domenicoluciani.com'
author:         'Domenico Luciani'
bio: 'Software engineer, runner, maker, computer vision fanatic and IT security lover. </br>Linkedin: <a href="https://linkedin.com/in/dlion">https://linkedin.com/in/dlion</a></br>Github: <a href="https://github.com/dlion">https://github.com/dlion</a>'
location: Palermo, Italy
website: https://domenicoluciani.com
gems:
    - jekyll-feed
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap

