name: Domenico Luciani
meta_description: "programming, coding, security, computer science"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://domenicoluciani.com'
google_analytics: false

# Details for the RSS feed generator
url:            'http://domenicoluciani.com/feed.xml'
author:         'Domenico Luciani'
gems:
    - jekyll-feed
    - jemoji
